In [1]:
import numpy as np
import pandas as pd
#masks = np.load('mask_images_large.npy')
df = pd.read_excel('Celltype_data.xlsx')
df.head()
def printProgressBar (iteration, total, prefix = '', suffix = '', decimals = 1, length = 100, fill = '█', printEnd = "\r"):
    # thanks to Greenstick on StackOverflow for the method 
   
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filledLength = int(length * iteration // total)
    bar = fill * filledLength + '-' * (length - filledLength)
    print(f'\r{prefix} |{bar}| {percent}% {suffix}', end = printEnd)
    # Print New Line on Complete
    if iteration == total: 
        print()

In [2]:
genes_data = df.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]].to_numpy()
class_data = df['class']
classes = np.unique(class_data)
print(classes)
print(genes_data)
print(genes_data.shape)

['L2/3 IT 1' 'L2/3 IT 2' 'L4/5 IT 1' 'L4/5 IT 2' 'L4/5 IT 3' 'L4/5 IT 4'
 'L4/5 IT 5' 'L4/5 IT 6' 'L5 PT 1' 'L5 PT 2' 'L5/6 IT 2' 'L5/6 IT 3'
 'L5/6 IT 4' 'L5/6 NP 1' 'L5/6 NP 2' 'L5/6 NP 3' 'L6 CT 2' 'L6 CT 4'
 'L6b 1' 'L6b 3' 'Lamp5 1' 'Lamp5 2' 'Lamp5 5' 'Lamp5 6' 'Pvalb 3'
 'Pvalb 4' 'Pvalb 5' 'Pvalb 6' 'Pvalb 7' 'Sst 10' 'Sst 11' 'Sst 13'
 'Sst 2' 'Sst 5' 'Sst 7' 'Sst 8' 'Sst 9' 'Sst Chodl 2' 'Vip 2' 'Vip 4'
 'Vip 5' 'Vip 6' 'Vip 7' 'Vip 8' 'Vip 9' 'ZNo markers']
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
(12229, 15)


In [3]:
print(genes_data.shape)
genes_data_m21014 = df.iloc[:,[1,3,4,5,6,7,8,9,11,12,13,15]].to_numpy()
#genes_data_m21014 = np.stack(genes_data[:,0], genes_data[:,2:8], genes_data[:,10:12], genes_data[:,14])
print(genes_data_m21014.shape)

(12229, 15)
(12229, 12)


In [4]:
from statistics import mode
from joblib import Parallel, delayed

def conversion(m_arr):
  c,ro,col = m_arr.shape
  print(m_arr.shape)
  assign = np.zeros((ro,col))
  Parallel(n_jobs=2)(delayed(convert_pixel(m_arr,i,j)) for i,j in range(ro),range(col))
  #for i in range(ro):
  #  for j in range(col):
      
      
      #assign[i,j] = convert_pixel(m_arr,i,j)
   #   printProgressBar((i * ro) + j , ro*col)
  return assign

def convert_pixel(m_arr,i,j):
  pos_cell_types = []
  for ind,gdat in enumerate(genes_data_m21014):
    mask_genes = m_arr[:,i,j]
    if((mask_genes == gdat).all()):
      pos_cell_types.append(class_data[ind])
  if(pos_cell_types != []):
    temp = mode(pos_cell_types)
    return np.where(classes == mode(pos_cell_types))[0]
  else:
    return len(classes) - 1



In [5]:
test = np.random.randint(2, size=(12,500,500))
thing = conversion(test)

(12, 500, 500)


TypeError: cannot unpack non-iterable function object